### Sign UP (Create user)

POST http://localhost:3000/users
content-type: application/json

{
  "username": "rafael@email.com",
  "password": "123456",
  "name": "Rafael Naves"
}

### Login

POST http://localhost:3000/login
content-type: application/json

{
  "username": "rafaelnaves", 
  "password": "123456"
}

### Get token with auto_login

GET http://localhost:3000/auto_login
content-type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.AMN4RUFphNOk_5rNRWYo_mynBlGWu29XlLSKYdYtfBs

### Get coins

GET http://localhost:3000/coins
content-type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.AMN4RUFphNOk_5rNRWYo_mynBlGWu29XlLSKYdYtfBs

### Get unique coin with asset_id

GET http://localhost:3000/coins/BTC
content-type: application/json
Authorization: Basic eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxfQ.AMN4RUFphNOk_5rNRWYo_mynBlGWu29XlLSKYdYtfBs