default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: crypto_wallet_api_development
  username: rafaelnaves
  password: 

test:
  <<: *default
  database: crypto_wallet_api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
